services:
  postgres:
    image: postgres:17.2
    container_name: spring-demo-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
