services:
  postgres:
    image: postgres:17.2
    container_name: spring-demo-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  mysql:
    image: mysql:9.2.0
    container_name: spring-demo-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
